### PR TITLE
Fixes and new features

### PR DESCRIPTION
**Pull request by ddequidt**
As you suggested, I create this PR to share few fixes and new features implemented while evaluating this tool.
Sorry I do only 1 PR for all those unrelated changes but I tried to separate changes per commit.
Feel free to pick or discard what you want.

### CODE REVIEW

**Comment by kasemir** [comment]
Great, thanks, I'll look through these

**Comment by kasemir** [comment]
Show pointer only on widget with action: Can't generally disable the pointer (pointer-events: none) because that also disables the middle-click-to-fetch-PV-name. Web pages also tend to allow selecting any section of plain text, which would be disabled.
I like changing the pointer for action buttons and text entries, so using that.

**Comment by kasemir** [comment]
Add rotation to Picture Widget: This handles the BOY 'permutation_matrix' for 90 degree rotations and flips. It crashes with NPE for display builder files that support a 'rotation' angle in degrees. Will see about handling both.

**Comment by kasemir** [comment]
I'll work down the commits and import as much as possible. Closing this PR.

**Comment by kasemir** [comment]
Handle tab_count in Tab widget: Please explain.

The BOY files use "tab_0_title", "tab_1_title" etc. to define the N tabs, and then N "<widget..." entries for the content. Do you have examples there the tab_count differs from the number of "tab_#_title" and/or included "<widget..." entries?

**Comment by kasemir** [comment]
Add rule support to Led widget: Please explain.

The LED has on and off colors, and sets the LED to one or the other based on the value of a PV.
Why would you use a rule to change those colors?

Send example display with one such LED.

**Comment by kasemir** [comment]
Polygon: OK on supporting the BOY way of setting fill color.

As for "fill_level", that was an SWT/Draw2d idea where there's an easy way to fill only a section of a poly line. "fill-opacity" looks very different, coloring the whole polygon.
Still, the basic approach of turning a "rectangle" or "polygon" into a "tank" by linking the "fill level" to a PV is not portable going forward. Instead, one needs to use a widget that's meant to indicate a PV, like the "tank".

**Comment by ddequidt** [comment]
> Handle tab_count in Tab widget: Please explain.
> 
> The BOY files use "tab_0_title", "tab_1_title" etc. to define the N tabs, and then N "<widget..." entries for the content. Do you have examples there the tab_count differs from the number of "tab_#_title" and/or included "<widget..." entries?

Some OPI are generated using an internal tool which create a fix number of tab_#_title and use tab_count to set the real number.
I just wanted to keep the same behavior than BOY runtime.

**Comment by ddequidt** [comment]
> Polygon: OK on supporting the BOY way of setting fill color.
> 
> As for "fill_level", that was an SWT/Draw2d idea where there's an easy way to fill only a section of a poly line. "fill-opacity" looks very different, coloring the whole polygon.
> Still, the basic approach of turning a "rectangle" or "polygon" into a "tank" by linking the "fill level" to a PV is not portable going forward. Instead, one needs to use a widget that's meant to indicate a PV, like the "tank".

Ok, I misunderstood the meaning of this field.

**Comment by ddequidt** [comment]
> Add rule support to Led widget: Please explain.
> 
> The LED has on and off colors, and sets the LED to one or the other based on the value of a PV.
> Why would you use a rule to change those colors?
> 
> Send example display with one such LED.

We use LED widget to show more than 2 states using rules:

            <rules>

              <rule name="Alarm LED ON State Color" prop_id="on_color" out_exp="false">
                <exp bool_exp="pv0== 0">
                  <value>
                    <color name="Normal Level Alarm" red="0" green="255" blue="0" />
                  </value>
                </exp>
                <exp bool_exp="pv0== 1">
                  <value>
                    <color name="Medium Level Alarm" red="255" green="255" blue="0" />
                  </value>
                </exp>
                <exp bool_exp="pv0== 2">
                  <value>
                    <color name="High Level Alarm" red="250" green="12" blue="14" />
                  </value>
                </exp>
                <exp bool_exp="pv0== 3">
                  <value>
                    <color name="Invalid Level Alarm" red="255" green="0" blue="255" />
                  </value>
                </exp>
                <pv trig="true">$(pv_name).SEVR</pv>
              </rule>
              <rule name="Alarm LED OFF State Color" prop_id="off_color" out_exp="false">
                <exp bool_exp="pv0== 3">
                  <value>
                    <color name="Invalid Level Alarm" red="255" green="0" blue="255" />
                  </value>
                </exp>
                <exp bool_exp="pv0== 2">
                  <value>
                    <color name="High Level Alarm" red="250" green="12" blue="14" />
                  </value>
                </exp>
                <pv trig="true">$(pv_name).SEVR</pv>
              </rule>
            </rules>

**Comment by kasemir** [comment]
Sorry, but that's abusing a feature in BOY. How would you do that in EDM? Or MEDM? Or PyDM? Or caQtDM? Or the next EPICS display manager? It simply doesn't port and puts you in a situation where you'll have to manually re-do your displays every 5-10 years.

If you have a PV with two states, use the LED widget.
If your PV really has 4 states (Normal Level, Medium Level, High Level, Invalid), use an LED with 4 states.
You example looks like you don't really care about the PV's value, but only the PV's severity.

So just create an LED with PV = ThatPVName.SEVR and 4 states:
0 = normal color
1 = minor color
2 = major color
3 = invalid color

No script/rule necessary.

If for some weird reason you care about both the value and the alarm state, and with value==0 you want to indicate Normal, Major, Invalid alarms, while with value==1 you want to indicate all alarm severities, then put that logic into a calc record on the IOC which provides the 'indicator value' of 0 to 3, and you're back to just a 4 state LED in the UI for that 'indicator PV'.
Again no script/rule necessary in the UI, and it will basically work with BOY, desktop display builder, web runtime, and quite easily port to the next display tool.

I'm still thinking about importing the LED rule addition similar to what you did, but conceptually the IOCs should provide PVs that are 'ready to display', not requiring a display tool that looks at N PVs to determine how to display the information. So turning the N states of your level into a PV on the IOC is better than duplicating that logic in every display tool.

**Comment by kasemir** [comment]
Ok on the tab_count, we can tell the code to ignore tab information beyond the requested tab_count.

**Comment by ddequidt** [comment]
> Sorry, but that's abusing a feature in BOY. How would you do that in EDM? Or MEDM? Or PyDM? Or caQtDM? Or the next EPICS display manager? It simply doesn't port and puts you in a situation where you'll have to manually re-do your displays every 5-10 years.
> 
> If you have a PV with two states, use the LED widget.
> If your PV really has 4 states (Normal Level, Medium Level, High Level, Invalid), use an LED with 4 states.
> You example looks like you don't really care about the PV's value, but only the PV's severity.
> 
> So just create an LED with PV = ThatPVName.SEVR and 4 states:
> 0 = normal color
> 1 = minor color
> 2 = major color
> 3 = invalid color
> 
> No script/rule necessary.
> 
> If for some weird reason you care about both the value and the alarm state, and with value==0 you want to indicate Normal, Major, Invalid alarms, while with value==1 you want to indicate all alarm severities, then put that logic into a calc record on the IOC which provides the 'indicator value' of 0 to 3, and you're back to just a 4 state LED in the UI for that 'indicator PV'.
> Again no script/rule necessary in the UI, and it will basically work with BOY, desktop display builder, web runtime, and quite easily port to the next display tool.
> 
> I'm still thinking about importing the LED rule addition similar to what you did, but conceptually the IOCs should provide PVs that are 'ready to display', not requiring a display tool that looks at N PVs to determine how to display the information. So turning the N states of your level into a PV on the IOC is better than duplicating that logic in every display tool.

I wanted to see if it was possible to make it work.
But you are right. We should not use it this way.

**Comment by kasemir** [comment]
Again I think we'll support those rules after all, but yes, for long term maintainability of your displays it's best to handle it via plain multi-state LEDs.

**Comment by kasemir** [comment]
On the multistate widget, I'm importing that verbatim since I've never used it and don't quite know how it works.

**Comment by kasemir** [comment]
Same with the bool monitor symbol.

**Comment by kasemir** [comment]
I think all your additions are now imported, thanks!

**Pull request closed without merging**
